### ISSUE TITLE
hi, I encountered an error

### ISSUE THREAD

**Issue by Kalmaegi** [muhammed-ayman/good-reads-books-reading-progress-scraper#1]
hey I'm getting an error while running this script, do you have the same problem there? I'm wondering if this has something to do with cookies

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.goodreads.com', port=443): Max retries exceeded with url: /review/list/69545251?shelf=currently-reading (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002C71F540430>: Failed to establish a new connection: [WinError 10060]

**Comment by aymnnattia** [comment]
Hey,

It's working fine on my behalf, it might be related to your internet connection; try to run a VPN while executing the code.

**Comment by Kalmaegi** [comment]
> Hey,
> 
> It's working fine on my behalf, it might be related to your internet connection; try to run a VPN while executing the code.

thanks!
